[platformio]
default_envs = src

[env]
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = spiffs

build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
    -I lib/audio/include
    -I lib/network/include
    -I managed_components/espressif__esp_tinyusb/include
    -Wno-error=stringop-overflow

[env:out]
platform = espressif32@~6.6.0
framework = espidf
board = seeed_xiao_esp32s3
board_build.sdkconfig = sdkconfig.out.defaults
upload_port = /dev/cu.usbmodem2101
build_flags = 
    ${env.build_flags}
    -D CONFIG_OUT_BUILD
    -D CONFIG_USE_ES8388
extra_scripts =
    pre:extra_script.py
    pre:tools/pio_prebuild_portal.py

[env:src]
platform = espressif32@~6.6.0
framework = espidf
board = seeed_xiao_esp32s3
board_build.sdkconfig = sdkconfig.src.defaults
upload_port = /dev/cu.usbmodem101
build_flags = 
    ${env.build_flags}
    -D CONFIG_SRC_BUILD
    -D CONFIG_USE_ES8388
extra_scripts =
    pre:extra_script.py
    pre:tools/pio_prebuild_portal.py

[env:native]
platform = native
test_framework = unity
test_build_src = no
lib_ignore = audio, network, control, config
build_flags =
    -I lib/audio/include
    -I lib/network/include
    -I lib/network/src
    -I lib/control/include
    -I lib/config/include
    -I test/native/shared
